<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName></SccProjectName>
    <SccProvider></SccProvider>
    <SccAuxPath></SccAuxPath>
    <SccLocalPath></SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
	  <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.22.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="PagedList.Core" Version="1.17.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Framework.Data\Framework.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dtos\Application\" />
  </ItemGroup>

</Project>
