<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName></SccProjectName>
    <SccProvider></SccProvider>
    <SccAuxPath></SccAuxPath>
    <SccLocalPath></SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
	  <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.22.2" />
    <PackageReference Include="PagedList.Core" Version="1.17.4" />
    <PackageReference Include="SecureIdentity" Version="1.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Framework.Data\Framework.Data.csproj" />
    <ProjectReference Include="..\Framework.Domain\Framework.Domain.csproj" />
    <ProjectReference Include="..\Framework.Infrastructure\Framework.Infrastructure.csproj" />
    <ProjectReference Include="..\Framework.Repositories\Framework.Repositories.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Using Include="System" />
		<Using Include="Framework.Tools" />
		<!-- Adicione outros namespaces que deseja usar globalmente -->
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="ApplicationServices\Platform\" />
	</ItemGroup>

</Project>
